name: marsfill-env
channels:
  - defaults
  - conda-forge
  - pytorch
dependencies:
  - _libgcc_mutex=0.1=main
  - _openmp_mutex=5.1=1_gnu
  - aiodns=3.5.0=py311h06a4308_0
  - aiohappyeyeballs=2.6.1=pyhd8ed1ab_0
  - aiohttp=3.12.15=py311hb25bd0a_0
  - aiosignal=1.4.0=pyhd8ed1ab_0
  - anyio=4.11.0=pyhcf101f3_0
  - aom=3.9.1=hac33072_0
  - arrow-cpp=21.0.0=h4e7ead5_0
  - attrs=25.4.0=pyh71513ae_0
  - aws-c-auth=0.9.0=hb25bd0a_2
  - aws-c-cal=0.9.2=h3ff94e8_1
  - aws-c-common=0.12.4=hb25bd0a_0
  - aws-c-compression=0.3.1=hb25bd0a_2
  - aws-c-event-stream=0.5.6=hb25bd0a_0
  - aws-c-http=0.10.4=hb25bd0a_0
  - aws-c-io=0.21.4=h3eb0749_0
  - aws-c-mqtt=0.13.3=hb25bd0a_0
  - aws-c-s3=0.8.7=h3ff94e8_0
  - aws-c-sdkutils=0.2.4=hb25bd0a_1
  - aws-checksums=0.2.7=hb25bd0a_1
  - aws-crt-cpp=0.34.0=h7934f7d_0
  - aws-sdk-cpp=1.11.638=hac3f51a_0
  - azure-core-cpp=1.14.1=h25a3319_1
  - azure-identity-cpp=1.10.1=h2dafd23_0
  - azure-storage-blobs-cpp=12.13.0=hdb19cb5_1
  - azure-storage-common-cpp=12.10.0=hf99dbc9_0
  - beautifulsoup4=4.14.2=pyha770c72_0
  - blas=1.0=openblas
  - blosc=1.21.6=hf7d4471_0
  - bottleneck=1.4.2=py311haa0f9ac_1
  - brotli-python=1.0.9=py311h6a678d5_9
  - bs4=4.14.2=hd8ed1ab_0
  - bzip2=1.0.8=hda65f42_8
  - c-ares=1.34.5=hb9d3cd8_0
  - ca-certificates=2025.10.5=hbd8a1cb_0
  - certifi=2025.10.5=pyhd8ed1ab_0
  - cffi=2.0.0=py311h4eded50_1
  - charset-normalizer=3.4.4=pyhd8ed1ab_0
  - colorama=0.4.6=pyhd8ed1ab_1
  - cuda-cudart=12.4.127=h99ab3db_0
  - cuda-cudart_linux-64=12.4.127=hd681fbe_0
  - cuda-cupti=12.4.127=h6a678d5_1
  - cuda-libraries=12.4.1=h06a4308_1
  - cuda-nvrtc=12.4.127=h99ab3db_1
  - cuda-nvtx=12.4.127=h6a678d5_1
  - cuda-opencl=12.4.127=h6a678d5_0
  - cuda-runtime=12.4.1=hb982923_0
  - cuda-version=12.4=hbda6634_3
  - datasets=4.3.0=pyhcf101f3_0
  - dav1d=1.2.1=h5eee18b_0
  - dill=0.4.0=pyhd8ed1ab_0
  - exceptiongroup=1.3.0=pyhd8ed1ab_0
  - expat=2.7.1=h6a678d5_0
  - ffmpeg=4.2.2=h20bf706_0
  - filelock=3.20.0=pyhd8ed1ab_0
  - freetype=2.14.1=ha770c72_0
  - freexl=2.0.0=hf309648_0
  - fribidi=1.0.10=h7b6447c_0
  - frozenlist=1.8.0=py311hbdd6827_0
  - fsspec=2025.9.0=pyhd8ed1ab_0
  - gdal=3.10.0=py311hbde30c8_13
  - geos=3.13.0=h5888daf_0
  - geotiff=1.7.4=h3551947_0
  - gflags=2.2.2=h5888daf_1005
  - giflib=5.2.2=hd590300_0
  - glog=0.5.0=h6a678d5_1
  - gmp=6.3.0=h6a678d5_0
  - gmpy2=2.2.1=py311h5eee18b_0
  - gnutls=3.6.15=he1e5248_0
  - h11=0.16.0=pyhd8ed1ab_0
  - h2=4.3.0=pyhcf101f3_0
  - hf-xet=1.1.8=py311h84c0859_0
  - hpack=4.1.0=pyhd8ed1ab_0
  - httpcore=1.0.9=pyh29332c3_0
  - httpx=0.28.1=pyhd8ed1ab_0
  - huggingface_hub=0.36.0=pyhd8ed1ab_0
  - hyperframe=6.1.0=pyhd8ed1ab_0
  - icu=73.2=h59595ed_0
  - idna=3.11=pyhd8ed1ab_0
  - importlib-metadata=8.5.0=py311h06a4308_0
  - jinja2=3.1.6=py311h06a4308_0
  - joblib=1.5.2=py311h06a4308_0
  - json-c=0.18=hee96239_0
  - keyutils=1.6.3=hb9d3cd8_0
  - krb5=1.21.3=h659f571_0
  - lame=3.100=h7b6447c_0
  - lcms2=2.17=h717163a_0
  - ld_impl_linux-64=2.44=h1aa0949_4
  - lerc=4.0.0=h0aef613_1
  - libabseil=20250127.0=cxx17_h6a678d5_0
  - libarchive=3.7.7=hfab0078_0
  - libavif16=1.3.0=h6395336_2
  - libbrotlicommon=1.0.9=h5eee18b_9
  - libbrotlidec=1.0.9=h5eee18b_9
  - libbrotlienc=1.0.9=h5eee18b_9
  - libcrc32c=1.1.2=h9c3ff4c_0
  - libcublas=12.4.5.8=h99ab3db_1
  - libcufft=11.2.1.3=h99ab3db_1
  - libcufile=1.9.1.3=h99ab3db_1
  - libcurand=10.3.5.147=h99ab3db_1
  - libcurl=8.16.0=h4e3cde8_0
  - libcusolver=11.6.1.9=h99ab3db_1
  - libcusparse=12.3.1.170=h99ab3db_1
  - libde265=1.0.15=h00ab1b0_0
  - libdeflate=1.22=h5eee18b_0
  - libedit=3.1.20250104=pl5321h7949ede_0
  - libev=4.33=hd590300_2
  - libevent=2.1.12=hf998b51_1
  - libexpat=2.7.1=hecca717_0
  - libffi=3.4.4=h6a678d5_1
  - libfreetype=2.14.1=ha770c72_0
  - libfreetype6=2.14.1=h73754d4_0
  - libgcc=15.2.0=h767d61c_7
  - libgcc-ng=15.2.0=h69a702a_7
  - libgdal-core=3.10.0=h7250d82_6
  - libgdal-jp2openjpeg=3.10.0=h671f25e_6
  - libgfortran=15.2.0=h69a702a_7
  - libgfortran-ng=15.2.0=h69a702a_7
  - libgfortran5=15.2.0=hcd61629_7
  - libgomp=15.2.0=h767d61c_7
  - libgrpc=1.71.0=h2d74bed_0
  - libheif=1.18.2=gpl_hffcb242_100
  - libhwy=1.3.0=h4c17acf_1
  - libiconv=1.18=h3b78370_2
  - libidn2=2.3.4=h5eee18b_0
  - libjpeg-turbo=3.1.1=hb25bd0a_0
  - libkml=1.3.0=haa4a5bd_1022
  - liblzma=5.8.1=hb9d3cd8_2
  - liblzma-devel=5.8.1=hb9d3cd8_2
  - libnghttp2=1.67.0=had1ee68_0
  - libnpp=12.2.5.30=h99ab3db_1
  - libnsl=2.0.1=hb9d3cd8_1
  - libnvfatbin=12.4.127=h7934f7d_2
  - libnvjitlink=12.4.127=h99ab3db_1
  - libnvjpeg=12.3.1.117=h6a678d5_1
  - libopenblas=0.3.30=pthreads_h94d23a6_3
  - libopenjpeg=2.5.4=hee96239_1
  - libopentelemetry-cpp-headers=1.21.0=ha770c72_1
  - libopus=1.3.1=h5eee18b_1
  - libpng=1.6.50=h421ea60_1
  - libprotobuf=5.29.3=h3cdef7c_1
  - libre2-11=2024.07.02=h6a678d5_0
  - librttopo=1.1.0=h97f6797_17
  - libspatialite=5.1.0=h1b4f908_12
  - libsqlite=3.50.4=h0c1763c_0
  - libssh2=1.11.1=hcf80075_0
  - libstdcxx=15.2.0=h8f9b012_7
  - libstdcxx-ng=15.2.0=h4852527_7
  - libtasn1=4.20.0=ha30cf84_0
  - libthrift=0.15.0=hd8eb582_4
  - libtiff=4.7.0=hc4654cb_2
  - libtorch=2.5.1=cpu_openblas_h526855f_4
  - libunistring=0.9.10=h27cfd23_0
  - libutf8proc=2.11.0=hb04c3b8_0
  - libuuid=2.41.2=he9a06e4_0
  - libuv=1.48.0=h5eee18b_0
  - libvpx=1.7.0=h439df22_0
  - libwebp=1.6.0=h9635ea4_0
  - libwebp-base=1.6.0=hd42ef1d_0
  - libxcb=1.17.0=h9b100fa_0
  - libxcrypt=4.4.36=hd590300_1
  - libxml2=2.13.9=h2c43086_0
  - libzlib=1.3.1=hb9d3cd8_2
  - lightning-utilities=0.15.2=py311h06a4308_0
  - lz4-c=1.9.4=h6a678d5_1
  - lzo=2.10=h280c20c_1002
  - markupsafe=3.0.2=py311h5eee18b_0
  - minizip=4.0.3=hf59b114_0
  - mpc=1.3.1=h5eee18b_0
  - mpfr=4.2.1=h5eee18b_0
  - mpmath=1.3.0=py311h06a4308_0
  - multidict=6.7.0=py311hee96239_0
  - multiprocess=0.70.15=py311h06a4308_0
  - muparser=2.3.5=h5888daf_0
  - ncurses=6.5=h2d0b736_3
  - nettle=3.7.3=hbbd107a_1
  - networkx=3.5=py311h06a4308_0
  - nlohmann_json=3.12.0=h54a6638_1
  - nomkl=3.0=0
  - numexpr=2.11.0=py311hccd6f0b_1
  - numpy=2.3.4=py311hc213724_0
  - numpy-base=2.3.4=py311hf387b04_0
  - nvidia-ml-py=13.580.82=pyhd8ed1ab_0
  - ocl-icd=2.3.2=h5eee18b_1
  - openh264=2.1.1=h4ff587b_0
  - openjpeg=2.5.4=h4e0627c_1
  - openssl=3.5.4=h26f9b46_0
  - opentelemetry-api=1.37.0=py311h06a4308_0
  - orc=2.2.0=h372e9aa_0
  - packaging=25.0=pyh29332c3_1
  - pandas=2.3.3=py311h505adc9_0
  - pcre2=10.44=hc749103_2
  - pillow=11.3.0=py311h98278a2_3
  - pip=25.2=pyh8b19718_0
  - proj=9.5.1=h0054346_0
  - prometheus-cpp=1.3.0=ha5d0236_0
  - propcache=0.3.1=py311h5eee18b_0
  - protobuf=5.29.3=py311he621ea3_0
  - psutil=7.1.2=py311haee01d2_1
  - pthread-stubs=0.3=h0ce48e5_1
  - pyarrow=21.0.0=py311h505adc9_0
  - pycares=4.10.0=py311ha137689_0
  - pycparser=2.22=pyh29332c3_1
  - pynvml=13.0.1=pyhd8ed1ab_0
  - pysocks=1.7.1=pyha55dd90_7
  - python=3.11.11=h9e4cc4f_2_cpython
  - python-dateutil=2.9.0.post0=pyhe01879c_2
  - python-tzdata=2025.2=pyhd8ed1ab_0
  - python-xxhash=3.5.0=py311h5eee18b_0
  - python_abi=3.11=2_cp311
  - pytorch=2.5.1=cpu_openblas_py311hff96616_4
  - pytorch-cuda=12.4=hc786d27_7
  - pytorch-mutex=1.0=cuda
  - pytz=2025.2=pyhd8ed1ab_0
  - pyyaml=6.0.2=py311h5eee18b_0
  - rav1e=0.7.1=h8fae777_3
  - re2=2024.07.02=hdb19cb5_0
  - readline=8.2=h8c095d6_2
  - regex=2025.9.1=py311hee96239_0
  - requests=2.32.5=pyhd8ed1ab_0
  - s2n=1.5.14=hdbd6064_0
  - safetensors=0.5.3=py311h448de89_0
  - scikit-learn=1.7.2=py311hc3e1efb_0
  - scipy=1.16.2=py311ha592af2_0
  - setuptools=80.9.0=pyhff2d567_0
  - six=1.17.0=pyhe01879c_1
  - sleef=3.5.1=h5eee18b_2
  - snappy=1.2.2=h03e3b7b_0
  - sniffio=1.3.1=pyhd8ed1ab_1
  - soupsieve=2.5=py311h06a4308_0
  - sqlite=3.50.4=hbc0de68_0
  - svt-av1=3.1.2=hecca717_0
  - sympy=1.14.0=py311h06a4308_0
  - threadpoolctl=3.5.0=py311h92b7b1e_0
  - tk=8.6.13=noxft_hd72426e_102
  - tokenizers=0.21.0=py311h5e3497e_0
  - torchmetrics=1.8.2=pyhd8ed1ab_0
  - torchvision=0.20.1=py311_cu124
  - tqdm=4.67.1=pyhd8ed1ab_1
  - transformers=4.55.4=pyhd8ed1ab_0
  - typing-extensions=4.15.0=h396c80c_0
  - typing_extensions=4.15.0=pyhcf101f3_0
  - tzdata=2025b=h78e105d_0
  - uriparser=0.9.8=hac33072_0
  - urllib3=2.5.0=pyhd8ed1ab_0
  - utf8proc=2.6.1=h5eee18b_1
  - uvloop=0.22.1=py311h939ff40_0
  - wheel=0.45.1=pyhd8ed1ab_1
  - x264=1!157.20191217=h7b6447c_0
  - x265=3.5=h924138e_3
  - xerces-c=3.2.5=hac6953d_0
  - xorg-libxau=1.0.12=h9b100fa_0
  - xorg-libxdmcp=1.1.5=h9b100fa_0
  - xxhash=0.8.0=h7f8727e_3
  - xz=5.8.1=hbcc6ac9_2
  - xz-gpl-tools=5.8.1=hbcc6ac9_2
  - xz-tools=5.8.1=hb9d3cd8_2
  - yaml=0.2.5=h280c20c_3
  - yarl=1.18.0=py311h5eee18b_0
  - zipp=3.21.0=py311h06a4308_0
  - zlib=1.3.1=hb9d3cd8_2
  - zstandard=0.24.0=py311h3d778a8_0
  - zstd=1.5.7=hb8e6e7a_2
prefix: /home/holanda/miniconda3/envs/marsfill-env
