name: Build and Push Docker Image to ECR

on:
  push:
    branches:
      - main

env:
  AWS_REGION: us-east-1
  ECR_REPOSITORY: marsfill-training-env
  AWS_ACCOUNT_ID: 109762776171
  ECR_REGISTRY: 109762776171.dkr.ecr.us-east-1.amazonaws.com

jobs:
  build-and-push:
    runs-on: [self-hosted, aws]
    permissions:
      contents: read

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ${{ env.AWS_REGION }}

      - name: Login to Amazon ECR Registries
        id: login-ecr
        uses: aws-actions/amazon-ecr-login@v2
        with:
          registries: ${{ env.AWS_ACCOUNT_ID }},763104351884

      - name: Define Image URI and Tags
        id: define-image-tags
        env:
          IMAGE_TAG: ${{ github.sha }}
        run: |
          echo "IMAGE_URI_SHA=${{ env.ECR_REGISTRY }}/${{ env.ECR_REPOSITORY }}:$IMAGE_TAG" >> $GITHUB_OUTPUT
          echo "IMAGE_URI_LATEST=${{ env.ECR_REGISTRY }}/${{ env.ECR_REPOSITORY }}:latest" >> $GITHUB_OUTPUT

      - name: Build, tag, and push image to ECR
        env:
          IMAGE_URI_SHA: ${{ steps.define-image-tags.outputs.IMAGE_URI_SHA }}
          IMAGE_URI_LATEST: ${{ steps.define-image-tags.outputs.IMAGE_URI_LATEST }}
        run: |
          # Constr√≥i a imagem
          echo "Construindo a imagem: $IMAGE_URI_SHA"
          docker build -t $IMAGE_URI_SHA -f Dockerfile .
          
          # Adiciona a tag 'latest'
          echo "Adicionando tag 'latest': $IMAGE_URI_LATEST"
          docker tag $IMAGE_URI_SHA $IMAGE_URI_LATEST
          
          # Envia a tag SHA
          echo "Enviando tag SHA..."
          docker push $IMAGE_URI_SHA
          
          # Envia a tag 'latest'
          echo "Enviando tag 'latest'..."
          docker push $IMAGE_URI_LATEST
